# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Barcode名'),
        ),
    ]
