# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20161222_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='name',
            field=models.CharField(help_text='最大只允许20个字符', max_length=20, verbose_name='引物名称'),
        ),
        migrations.AlterField(
            model_name='primer',
            name='sequence',
            field=models.CharField(help_text='最大只允许50个字符', max_length=50, verbose_name='序列'),
        ),
    ]
