# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_auto_20161223_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primer',
            name='sequence',
        ),
        migrations.AddField(
            model_name='primer',
            name='forward_primer',
            field=models.CharField(default=1, help_text='最大只允许50个字符', max_length=50, verbose_name='正向序列'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primer',
            name='reverse_primer',
            field=models.CharField(default=1, help_text='最大只允许50个字符', max_length=50, verbose_name='反向序列'),
            preserve_default=False,
        ),
    ]
