# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_auto_20161226_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'verbose_name': '实验管理', 'verbose_name_plural': '实验管理'},
        ),
    ]
