# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='最大只允许15个字符', max_length=15, unique=True, verbose_name='合同号')),
                ('name', models.CharField(help_text='最大只允许20个字符', max_length=20, verbose_name='合同名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='单价')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总款')),
                ('send_date', models.DateField(blank=True, verbose_name='合同寄出日')),
                ('tracking_number', models.CharField(max_length=15, unique=True, verbose_name='快递单号')),
                ('receive_date', models.DateField(blank=True, verbose_name='合同寄回日')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='销售')),
            ],
            options={
                'verbose_name_plural': '合同管理',
                'verbose_name': '合同管理',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='发票抬头')),
                ('period', models.CharField(choices=[('FIS', '首款'), ('FIN', '尾款')], default='FIS', max_length=3, verbose_name='款期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='开票金额')),
                ('submit', models.BooleanField(verbose_name='提交开票')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Contract', verbose_name='合同')),
            ],
            options={
                'verbose_name_plural': '开票管理',
                'verbose_name': '开票管理',
            },
        ),
    ]
