# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='send_date',
            field=models.DateField(default=None, verbose_name='合同寄出日'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='快递单号'),
        ),
    ]
