# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0006_auto_20170105_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='receive_date',
            field=models.DateField(null=True, verbose_name='合同寄到日'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='快递单号'),
        ),
    ]
