# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0007_auto_20170109_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='range',
            field=models.CharField(default=1, help_text='最大只允许20个字符', max_length=20, verbose_name='价格区间'),
            preserve_default=False,
        ),
    ]
