# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0008_contract_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.TextField(default=1, verbose_name='备注'),
            preserve_default=False,
        ),
    ]
