# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0009_invoice_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '开票申请', 'verbose_name_plural': '开票申请'},
        ),
    ]
