# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mm', '0006_auto_20170105_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='到账金额')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='到账日期')),
            ],
            options={
                'verbose_name': '进账管理',
                'verbose_name_plural': '进帐管理',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(max_length=12, verbose_name='发票单号')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='开票日期')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mm.Invoice', verbose_name='发票')),
            ],
            options={
                'verbose_name': '发票管理',
                'verbose_name_plural': '发票管理',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fm.Invoice', verbose_name='发票'),
        ),
    ]
