# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='开票日期'),
        ),
    ]
