# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0002_auto_20170105_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(verbose_name='到账时间'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='开票时间'),
        ),
    ]
