# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0003_auto_20170109_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(null=True, verbose_name='开票日期'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_code',
            field=models.CharField(max_length=12, verbose_name='发票号码'),
        ),
    ]
