# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0005_auto_20170111_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='send_date',
            field=models.DateField(null=True, verbose_name='寄出日期'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='快递单号'),
        ),
    ]
