# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='客户名')),
                ('organization', models.CharField(max_length=40, verbose_name='单位')),
            ],
            options={
                'verbose_name_plural': '客户管理',
                'verbose_name': '客户管理',
            },
        ),
    ]
