# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, help_text='最大只允许50个字符', max_length=50, verbose_name='地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='最大只允许12个字符', max_length=12, verbose_name='客户名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.CharField(help_text='最大只允许40个字符', max_length=40, verbose_name='单位'),
        ),
    ]
