# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_auto_20161222_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='call',
            field=models.PositiveIntegerField(default=1, verbose_name='电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='linker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(default=1, verbose_name='手机'),
            preserve_default=False,
        ),
    ]
