# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='contract_data',
            field=models.PositiveIntegerField(default=1, verbose_name='合同数据量'),
            preserve_default=False,
        ),
    ]
