# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_auto_20161223_1153'),
        ('pm', '0004_auto_20161223_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='最大只允许15个字符', max_length=15, verbose_name='文库名')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Barcode', verbose_name='index号')),
                ('primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.Primer', verbose_name='类型')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.Sample', verbose_name='样品名')),
            ],
        ),
    ]
