# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_library_sequenceinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequenceinfo',
            options={'verbose_name': '排机管理', 'verbose_name_plural': '排机管理'},
        ),
        migrations.AddField(
            model_name='sequenceinfo',
            name='apply_data',
            field=models.PositiveIntegerField(default=1, verbose_name='排机量'),
            preserve_default=False,
        ),
    ]
