# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_auto_20161223_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenceinfo',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pm.Library', verbose_name='文库名'),
            preserve_default=False,
        ),
    ]
