# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_sequenceinfo_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': '排机管理', 'verbose_name_plural': '排机管理'},
        ),
        migrations.AlterModelOptions(
            name='sequenceinfo',
            options={'verbose_name': '排机表', 'verbose_name_plural': '排机表'},
        ),
    ]
