# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0008_auto_20161223_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequenceinfo',
            options={'verbose_name': '排机信息', 'verbose_name_plural': '排机信息'},
        ),
        migrations.AddField(
            model_name='sample',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pm.Library', verbose_name='排机文库'),
            preserve_default=False,
        ),
    ]
