# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0009_auto_20161223_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='library',
        ),
    ]
