# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0010_remove_sample_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '1.项目管理', 'verbose_name_plural': '1.项目管理'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': '2.样品管理', 'verbose_name_plural': '2.样品管理'},
        ),
    ]
