# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0012_sample_experiment_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='experiment_num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='实验次数'),
        ),
    ]
