# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0001_initial'),
        ('pm', '0013_auto_20161229_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目管理', 'verbose_name_plural': '项目管理'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': '样品管理', 'verbose_name_plural': '样品管理'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract_number',
        ),
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mm.Contract', verbose_name='合同'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='extract_num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='提取次数'),
        ),
        migrations.AddField(
            model_name='sample',
            name='lib_16S_num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='16S建库次数'),
        ),
        migrations.AddField(
            model_name='sample',
            name='lib_ITS_num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ITS建库次数'),
        ),
        migrations.AddField(
            model_name='sample',
            name='lib_frag_num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='小片段建库次数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='最多只允许20个字符', max_length=20, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NST', '未启动'), ('SSB', '样品提交'), ('QC', '质检完成'), ('LIB', '建库完成'), ('SEQ', '测序完成'), ('END', '完结'), ('FIN', '完成'), ('PAU', '暂停')], default='NST', max_length=3, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='experiment_num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='质检次数'),
        ),
    ]
