# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0014_auto_20170105_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='experiment_num',
            new_name='qc_num',
        ),
    ]
